### Delete graph
DELETE http://localhost:3000/redisgraph/graph

### Create organization
POST http://localhost:3000/redisgraph/organization
Content-Type: "application/json"

{
    "name": "Google"
}

### Get all organizations
GET http://localhost:3000/redisgraph/organization/all

### Get organization by name
GET http://localhost:3000/redisgraph/organization/Google

### Create person
POST http://localhost:3000/redisgraph/person
Content-Type: "application/json"

{
    "name": "Alberto Spinella",
    "age": 23
}

### Get all person
GET http://localhost:3000/redisgraph/person/all

### Get person by name
GET http://localhost:3000/redisgraph/person/Alberto%20Spinella

### Hire
POST http://localhost:3000/redisgraph/hire
Content-Type: "application/json"

{
    "organizationName": "Google",
    "personName": "Alberto Spinella"
}

### Own
POST http://localhost:3000/redisgraph/own
Content-Type: "application/json"

{
    "organizationName": "Google",
    "personName": "Mario Rossi"
}

### Knows
POST http://localhost:3000/redisgraph/knows
Content-Type: "application/json"

{
    "person1": "Alberto Spinella",
    "person2": "Mario Rossi",
    "since": "april"
}

### Stress
GET http://localhost:3000/redisgraph/stress