curl -X POST http://localhost:3000/redisgraph/organization -H "Content-Type: application/json" -d '{"name":"Google"}'

curl -X POST http://localhost:3000/redisgraph/person -H "Content-Type: application/json" -d '{"name":"Alberto","age":"23"}'
curl -X POST http://localhost:3000/redisgraph/person -H "Content-Type: application/json" -d '{"name":"Alessandro","age":"22"}'
curl -X POST http://localhost:3000/redisgraph/person -H "Content-Type: application/json" -d '{"name":"Mario","age":"29"}'
curl -X POST http://localhost:3000/redisgraph/person -H "Content-Type: application/json" -d '{"name":"Luigi","age":"31"}'
curl -X POST http://localhost:3000/redisgraph/hire -H "Content-Type: application/json" -d '{"organizationName":"Google","personName":"Alberto"}'
curl -X POST http://localhost:3000/redisgraph/hire -H "Content-Type: application/json" -d '{"organizationName":"Google","personName":"Alessandro"}'
curl -X POST http://localhost:3000/redisgraph/own -H "Content-Type: application/json" -d '{"personName":"Mario","organizationName":"Google"}'
curl -X POST http://localhost:3000/redisgraph/own -H "Content-Type: application/json" -d '{"personName":"Luigi","organizationName":"Google"}'

curl -X POST http://localhost:3000/redisgraph/knows -H "Content-Type: application/json" -d '{"person1":"Alberto","person2":"Mario","since":"april"}'
curl -X POST http://localhost:3000/redisgraph/knows -H "Content-Type: application/json" -d '{"person1":"Alberto","person2":"Luigi","since":"april"}'
curl -X POST http://localhost:3000/redisgraph/knows -H "Content-Type: application/json" -d '{"person1":"Alberto","person2":"Alessandro","since":"september"}'
curl -X POST http://localhost:3000/redisgraph/knows -H "Content-Type: application/json" -d '{"person1":"Mario","person2":"Alberto","since":"april"}'
curl -X POST http://localhost:3000/redisgraph/knows -H "Content-Type: application/json" -d '{"person1":"Mario","person2":"Luigi","since":"longtime"}'
curl -X POST http://localhost:3000/redisgraph/knows -H "Content-Type: application/json" -d '{"person1":"Mario","person2":"Alessandro","since":"september"}'
curl -X POST http://localhost:3000/redisgraph/knows -H "Content-Type: application/json" -d '{"person1":"Luigi","person2":"Alberto","since":"april"}'
curl -X POST http://localhost:3000/redisgraph/knows -H "Content-Type: application/json" -d '{"person1":"Luigi","person2":"Mario","since":"longtime"}'
curl -X POST http://localhost:3000/redisgraph/knows -H "Content-Type: application/json" -d '{"person1":"Luigi","person2":"Alessandro","since":"september"}'
curl -X POST http://localhost:3000/redisgraph/knows -H "Content-Type: application/json" -d '{"person1":"Alessandro","person2":"Alberto","since":"september"}'
curl -X POST http://localhost:3000/redisgraph/knows -H "Content-Type: application/json" -d '{"person1":"Alessandro","person2":"Mario","since":"september"}'
curl -X POST http://localhost:3000/redisgraph/knows -H "Content-Type: application/json" -d '{"person1":"Alessandro","person2":"Luigi","since":"september"}'
